### ISSUE TITLE
my installation features with proxmox LXC

### ISSUE THREAD

**Issue by Cmoi20** [pabloromeo/clusterplex#1]
######## installation using proxmox #######

As I tryed installing in a proxmox cluster with LXC and have many issue before this runing well, I offer you my functional solution based in this tools.
1 Plex server :
- create a LXC container ubuntu  x64 based with no priviliged option inactivated
- create 5 folders :
         * /var/lib/plexmediaserver
         * /usr/lib/plexmediaserver
         * /data    // in my example, this folder contain plex data
         * /app
         * /opt/clusterplex
I personaly use nfs folder for data and usr sub directory so, you can enable nfs in lxc options.
for var sub folder, I mount a local folder from my proxmox server (I don't know why nfs share not working)
- install plex on it with .deb file.
- rename "/usr/lib/plexmediaserver/Plex Transcoder" to "/usr/lib/plexmediaserver/originalTranscoder"
- go to /opt/clusterplex folder and execute :
         * /app
         * /opt/clusterplex
         * apt-get update
         * apt-get install curl gcc g++ make git rsync
         * git clone https://github.com/pabloromeo/clusterplex.git
         * cd clusterplex/pms
         * rsync -a ./* /app/
         * curl -sL https://deb.nodesource.com/setup_10.x | bash -
         * apt-get update
         * apt-get install nodejs
         * cd /app
         * npm install
         * cp /app/transcoder-shim.sh "/usr/lib/plexmediaserver/Plex Transcoder"
         
you can edit /app/transcoder.js with this start of file : 
################
const ORCHESTRATOR_URL = process.env.ORCHESTRATOR_URL || 'http://orchestratorIP:3500'
const TRANSCODER_PATH = process.env.TRANSCODER_PATH || '/usr/lib/plexmediaserver/'
const TRANSCODER_NAME = process.env.TRANSCODER_NAME || 'Plex Transcoder'
const TRANSCODER_LOCAL_NAME = process.env.TRANSCODER_LOCAL_NAME || 'originalTranscoder'
const PMS_IP = process.env.PMS_IP || '192.168.0.1'
const TRANSCODER_VERBOSE = process.env.TRANSCODER_VERBOSE || '0'
// Operating mode:
// local
// remote
// both
const TRANSCODE_OPERATING_MODE = process.env.TRANSCODE_OPERATING_MODE || 'remote'
#################

normaly, just change your plex server ip and your orchestrator server ip.
         
2 Orchestrator :
- create a LXC container debian  x64 based with no priviliged option inactivated
- create 2 folders : 
         * /app
         * /opt/clusterplex
install needed features :
         * apt-get update
         * apt-get install curl gcc g++ make git rsync
         * git clone https://github.com/pabloromeo/clusterplex.git
         * cd clusterplex/orchestrator
         * rsync -a ./* /app/
         * curl -sL https://deb.nodesource.com/setup_10.x | bash -
         * apt-get update
         * apt-get install nodejs
         * cd /app
         * npm install
         * node server.js
         
and let run service to check. when all is finish, you can kill process and user pm2 to autostart sercvices :
         * cd /app
         * pm2 start server.js
         * pm2 save

3 Worker :
- create a LXC container debian  x64 based with no priviliged option inactivated
- create 5 folders :
         * /var/lib/plexmediaserver
         * /usr/lib/plexmediaserver
         * /data    // in my example, this folder contain plex data
         * /app
         * /opt/clusterplex
 mount folders same as plex server.
 install needed features :
          * apt-get update
         * apt-get install curl gcc g++ make git rsync
         * git clone https://github.com/pabloromeo/clusterplex.git
         * cd clusterplex/worker
         * rsync -a ./* /app/
         * curl -sL https://deb.nodesource.com/setup_10.x | bash -
         * apt-get update
         * apt-get install nodejs
         * cd /app
         * npm install
edit /app/worker.js file with this start :
###########################
const STAT_CPU_INTERVAL = process.env.STAT_CPU_INTERVAL || 10000
const ORCHESTRATOR_URL = process.env.ORCHESTRATOR_URL || 'http://orchestratorIP:3500'
const TRANSCODER_PATH = process.env.TRANSCODER_PATH || '/usr/lib/plexmediaserver/'
const TRANSCODER_NAME = process.env.TRANSCODER_NAME || 'originalTranscoder'
###########################

normaly, just change your orchestrator server ip.
run service : 
         * node worker.js
         
and let run service to check. when all is finish, you can kill process and user pm2 to autostart sercvices :
         * cd /app
         * pm2 start worker.js
         * pm2 save

if you need more informations, please ask.

**Comment by Cmoi20** [comment]
keep available for update process

**Comment by pabloromeo** [comment]
Hey, how's it going? Oh, I don't actually run this on proxmox, just run it directly on a docker swarm cluster using docker, so I'm not familiar with it.
The images I run on ARM are here: https://hub.docker.com/r/pabloromeo/clusterplex

Were you not able to just build docker images for your architecture or run those?

I'm wondering why you had to make so many changes and install steps. The pms image already includes plex, there's no need to manually install it, and the process.env settings are there so you can override directly as environment variables when starting up docker so you don't have to manually change the code if you want to change those settings.

BTW, sorry for now writing any instructions on how to actually run any of this lol, I haven't found the time to provide a proper example of docker compose files or docker stack files to set this up.

**Comment by pabloromeo** [comment]
Ah, I just realized you are using a different type of virtualization and not docker. Yeah, sounds like you would have to replicate what the Dockerfiles are currently doing for each one of the 3 parts.

**Comment by Cmoi20** [comment]
That's not an issue but I cannot push this information in wiki. this was informations for peoples who want using your tools with lxc container.

**Comment by Cmoi20** [comment]
all running well

**Comment by pabloromeo** [comment]
Ah, perfect! I'm glad you found it useful :)

Also, feel free to upvote this feature request for plex, which would allow us all to optimize in parallel across entire clusters: https://forums.plex.tv/t/optimize-transcode-content-in-parallel/547731

**Comment by Cmoi20** [comment]
just voted

**Comment by pabloromeo** [comment]
FYI, I finally managed to write some documentation around this, in the README, and added a bit of functionality :)

**Comment by Nullvoid3771** [comment]
@Cmoi20 

Just a shot in the dark since you use proxmox I’m using proxmox, but instead of it being in LXC I’m using two Ubuntu vm’s then running docker swarm inside the vm with portainer creating the Clusterplex using stack template. Just curious if you recognize an issue with my setup? Not too sure if proxmox is causing me issues or if it’s portainer or a configuration issue with clusterplex, but I can’t set the workers to transcode only works if I keep transcoding local to pms.

https://github.com/pabloromeo/clusterplex/issues/332
