### ISSUE TITLE
Optimized Versions

### ISSUE THREAD

**Issue by christianmerges** [pabloromeo/clusterplex#127]
When I try to generate optimized versions, only one movie is processed at once. Is it possible to let the worker do this job and for an example in idle time, let all the workers prepare optimized versions for movies?

**Comment by christianmerges** [comment]
OK i fixed codec download by changing permission of codecs folder to 777

**Comment by pabloromeo** [comment]
Yes! It would be amazing if Plex supported that.
We could take way more advantage of parallel workers
I even posted it on https://forums.plex.tv/t/optimize-transcode-content-in-parallel/547731
Unfortunately I haven't found a way to get Plex to actually process multiple items from the queue simultanously, even when there are plenty of resources to do so with multiple workers. Plex seems to be hardcoded to only support one at a time :(

You can have workers doing playback transcoding and another worker optimizing content, but that's about as far as Plex seems to support unfortunately.
