### ISSUE TITLE
Documentation Update for PMS_IP variable

### ISSUE THREAD

**Issue by imdebating** [pabloromeo/clusterplex#150]
In fact, if you want to give it a shot, just set the PMS_IP value to the string "plex". Since "plex" is the service name in the stack it should resolve to it's IP.

I should actually explain it better in the docs. The PMS_IP is actually sent over to the orchestrator and it's used by the worker to later report transcode status back to the actual Plex server. So technically it's just the location at where to report back, and in the case of Swarm, that can be any node in the cluster. It's used to replace a hardcoded 127.0.0.1 specified by Plex in the transcode instructions. Come to think of it, maybe I can find a workaround so that this setting isn't even mandatory and resolved internally to the IP assigned by docker to the "plex" service. And just have the PMS_IP as an override in case someone runs Plex OUTSIDE of the cluster.

_Originally posted by @pabloromeo in https://github.com/pabloromeo/clusterplex/issues/123#issuecomment-1073031429_

**Comment by pabloromeo** [comment]
Thanks @imdebating , I just added the comment around PMS_IP in the README.
https://github.com/pabloromeo/clusterplex/pull/158
