### ISSUE TITLE
Support arm64 workers

### ISSUE THREAD

**Issue by donicrosby** [pabloromeo/clusterplex#151]
**Is your feature request related to a problem? Please describe.**
When downloading the codecs for the plex media server there is no arm64 in the architecture switch

**Describe the solution you'd like**
add arm64 to the codec switch so that things like the NVIDIA Jetson Nano can download the needed codecs

**Describe alternatives you've considered**
forking the worker docker mod and adding it myself

**Additional context**
N/A

**Comment by pabloromeo** [comment]
Ah, true, arm64 is missing. 
I don't have any arm64 to test on, to see what the corresponding strings are when identifying that arch, and also to determine the proper urls used by plex for arm64 codecs.
Feel free to open a PR if you have a working variant.

**Comment by donicrosby** [comment]
Found the needed CLUSTERPLEX_PLEX_CODEC_ARCH which is `linux-aarch64-standard`

Not sure what I need to use to find the INTERNAL_PLEX_MEDIA_SERVER_INFO_MODEL, unless that's just what spits out when I do `cat /proc/cpuinfo` in which case it's armv8l

**Comment by donicrosby** [comment]
I believe I have the correct values, I am now having issues with the spawn it's returning ENOENT when the subprocess is trying to spawn

**Comment by pabloromeo** [comment]
I've merged into the dev branch, so once the build finishes, it will be available under the "dev" tag for all components. If you can, please test that build and if all goes well I'll merge into master and create a new tagged release.

**Comment by donicrosby** [comment]
The dev branch works on my Clusterplex instance

**Comment by pabloromeo** [comment]
https://github.com/pabloromeo/clusterplex/releases/tag/v1.3.14 includes ARM64 support. thanks so much.
