### ISSUE TITLE
Possible Plex Update removed required variable for codecs

### ISSUE THREAD

**Issue by jean1880** [pabloromeo/clusterplex#163]
**Describe the bug**
When starting a worker container, codecs fail to download as `CLUSTERPLEX_PLEX_CODECS_VERSION` is undefined in start.sh, this results in broken URLS when trying to fetch codecs from `https://downloads.plex.tv/codecs/${CLUSTERPLEX_PLEX_CODECS_VERSION}/${CLUSTERPLEX_PLEX_CODEC_ARCH}/${codec}.so` 

**To Reproduce**
1. Start worker container using dockermods configuration

**Expected behavior**
Codecs to download without 404 errors

**Desktop (please complete the following information):**
 - OS: Unraid, linux docker
 - Version: 6.10.3

**Additional context**
I haven't started doing deep dive into the image yet, but reaching out in case I missed something critical, or important that you may have encountered before, if not, was going to fork the repo and do some builds on my own end to see what I could figure out.

**Comment by pabloromeo** [comment]
Oh, that doesn't sound good. If Plex has obfuscated the codec version within their Transcoder executable that will be quite a problem.
We extract it using:
`strings "Plex Transcoder" | grep -Po '[0-9a-f]{7}-[0-9]{4}$'`

I'm currently in the middle of rebuilding my infrastructure so I don't have a clusterplex instance running at the moment.

Could you run that command in `/usr/lib/plexmediaserver` and share the output? I'll see if I can find a way to get a temporary instance up and running to test it myself.

**Comment by jean1880** [comment]
Yeah, I was looking at your source code, to isolate the issue, if you haven't yet, I was going to put some time into it this weekend. 

I am HOPING that they maybe just changed the name to "Plex Universal Transcoder", perhaps as part of their migration to their new transcoder, but I have a gut feeling it may not be so easy. Will let you know the results of my own investigation if I get to it first.

**Comment by pabloromeo** [comment]
I just manually tested it on my NAS real quick, and the commands still work on the latest version:

Plex v1.28.2.6106 release returns the following:
- Plex full version number: 1.28.2.6106-44a5bbd28
- Codecs version: c4efa15-4365

Could you provide a bit more info about your install and logs to determine what might be happenning?
Any chance your worker might not have the "strings" utility installed? It should have been installed by the worker dockermod during startup. We can see that in the logs.

**Comment by jean1880** [comment]
Accessing the worker image in shell, yeah, it looks like `strings` command was not installed
![image](https://user-images.githubusercontent.com/2329137/187324327-f969bf85-99f3-4abd-b892-16d2f4b3cf96.png)

**Comment by jean1880** [comment]
Looking at the `apt install` step, I don't see a specific issue with installing `binutils` 

![image](https://user-images.githubusercontent.com/2329137/187325147-5d812643-02a5-411b-a699-071d7973ca06.png)

I can investigate more later, if it is working for you, it may just be a configuration issue on my end, so this gives me a good direction to look, thanks. 

If I find anything that actually looks like a bug with this repo, I will open something specific to that, I will close this for now.

**Comment by pabloromeo** [comment]
Oh, yeah, but all those errors there not being able to write to `/tmp` are a bit telling. Sounds like a permissions issue on the bind mount used against `/tmp`. Try changing permissions to 777 on `/tmp` and trying again.
This same behavior was reported in issue https://github.com/pabloromeo/clusterplex/issues/124, and it's usually due to permissions on the temp mount.
