### ISSUE TITLE
kubernetes / i915 gpu, no hardware acceleration option

### ISSUE THREAD

**Issue by cranky-coder** [pabloromeo/clusterplex#195]
I have my cluster configured to run the workers on nodes that have the i915 intel gpu enabled.  I have it configured in the resource limits and they are being assigned to the right nodes.  But when I watch the gpu usage on the nodes, there is 0 gpu work happening but the cpu's are getting hit hard.  In the settings for the clusterplex instance i do not see the option to enable hardware transcoding. 

![image](https://user-images.githubusercontent.com/6988745/210622600-2abcdc88-e0bd-4f53-a8f3-ebfb6fadd938.png)

Any suggestions?

**Comment by cranky-coder** [comment]
Checking that last one!!   I have the device drivers in the nodes, and updated the deployment, but that ENV I didn't change!! that might be it!

**Comment by pabloromeo** [comment]
Nice! Yeah, I'm not sure what the proper value for `FFMPEG_HWACCEL` would be though, for i915, not sure if it's `QSV` or `VAAPI` or something else.
Once you get it working, if you want to share the deployment yaml and info on running the driver I can add it to the documentation, as an example with HW transcoding.

**Comment by meyayl** [comment]
This is what you get on i915 with `FFMPEG_HWACCEL: QSV`
```
plex_worker  | Unrecognized hwaccel: QSV.
plex_worker  | Supported hwaccels: cuda vaapi drm opencl
```

**Comment by cranky-coder** [comment]
I used vaapi.  Works so far.  Gonna do a PR hopefully this weekend with my full yaml.

**Comment by pabloromeo** [comment]
Awesome!! Glad to hear it's working.

**Comment by pabloromeo** [comment]
Hi @cranky-coder, if you ultimately got i915 to work on your k8s cluster, could you share your config? I believe others, such as in this issue https://github.com/pabloromeo/clusterplex/issues/223 may benefit from a working example.

**Comment by evanrich** [comment]
Curious about this too.  I have the i915 drivers installed, intel pods all show 915 available, but the workers can't find the gpu.   I tried setting the FFMPEG_HWACCEL=vaapi but it doesn't seem to find them.  running talos version of kubernetes if that helps.    I've seen that you may need to set a pod secuirity policy to allow privledged access, but i dont think the chart supports that.
