### ISSUE TITLE
Codec download issue

### ISSUE THREAD

**Issue by kicker83** [pabloromeo/clusterplex#196]
Hi!

Today I restarted my workers and I notice that codecs are not being found in plex downloads.

`--2023-01-13 11:34:46--  https://downloads.plex.tv/codecs//linux-x86_64-standard/librv20_decoder.so
Resolving downloads.plex.tv (downloads.plex.tv)... 104.18.19.96, 104.18.18.96, 2606:4700::6812:1360, ...
Connecting to downloads.plex.tv (downloads.plex.tv)|104.18.19.96|:443... connected.
HTTP request sent, awaiting response... 404 Not Found`

Please, could you provide a new location or update the worker image with new URLs?

Thanks in advance!

**Comment by pabloromeo** [comment]
Hi!
If you look at the beginning of the logs in the worker, you might be seeing errors related to unreachable hosts or timeouts against archive.ubuntu.com.
That was preventing additional tooling from being installed, causing the error you saw.

I restarted the worker again after a while, and the apt sources are back it seems, and the worker installs the tools and is able to fetch codes.
Could you try again to see if it has been resolved?

**Comment by kicker83** [comment]
Yes, now its working perfect! Thanks :)
