### ISSUE TITLE
clusterplex_dockermod:latest could not be found on ghcr.io

### ISSUE THREAD

**Issue by n1coh** [pabloromeo/clusterplex#221]
Hello, I've followed the installation instructions for k8s, and everything seems to be right for me.
But when initializing the cluster-pms pods I get this error:
[mod-init] pabloromeo/clusterplex_dockermod:latest could not be found on ghcr.io

It's a single node k3s on hetzner.
It seems to be a network problem at cluster level, but I confess I don't know where to look for the problem.

It's more a request for help than a bug.
Thank you for your help and this very interesting project.

**Comment by n1coh** [comment]
I've found the problem, it's the hetzner firewall that I had badly configured.

You can delete this ticket if you wish.

Sorry for the inconvenience

**Comment by pabloromeo** [comment]
Ah, no worries! Thanks :)
