### ISSUE TITLE
Issue with Direct Stream

### ISSUE THREAD

**Issue by konSMASH** [pabloromeo/clusterplex#237]
Hello, I am a bit new to Linux, but I got ClusterPlex setup and working with 8 total servers. I am running into an issue where if a user has Direct Stream enabled, the video will get stuck buffering at 33% until it fails playback.

Direct Play is working fine, but Direct Stream seems to be an issue. When users disable Direct Stream, it seems to resolve the problem. Is this a known issue or is there something I can do to fix this issue?

**Comment by konSMASH** [comment]
I swapped the codecs folder from shared to download on each worker and it seems to have resolved the issue.

**Comment by pabloromeo** [comment]
Ah, yes, sharing the `codecs` across workers could cause the downloaded codec to be corrupted if multiple workers start at the same time, since they all start by downloading codecs from Plex if they don't exist.
