### ISSUE TITLE
Remote transcode failing, but showing it works in the logs.

### ISSUE THREAD

**Issue by konSMASH** [pabloromeo/clusterplex#263]
**Describe the bug**
Hello! I have been running ClusterPlex for a few months with a few small quirks here and there. However, today I noticed that my remote transcoding has actually been failing and I didn't realize it. Everything was just falling back to local. Currently what I am seeing is Plex sees a video started, sends the request to Orchestrator, Orchestrator then send the request to a worker, and it shows that it's working. However, the video will never end up playing. I can sometimes get it to work if I skip ahead 30 seconds. I'm not sure what is 

I have a single server within my Docker Swarm handling PMS and Orchestrator, and 6 separate servers within the swarm acting as my workers. They are all labelled so I can direct my services on the servers I'd like them to be on.

Please let me know of any logs you'd like me to pull, I just didn't want to flood the initial report with them if they aren't necessary.

This is my current docker-compose.yml file:

version: '3.8'

services:
  plex:
    image: ghcr.io/linuxserver/plex:latest
    deploy:
      placement:
        constraints:
          - node.labels.master ==  true
    environment:
      DOCKER_MODS: "ghcr.io/pabloromeo/clusterplex_dockermod:latest"
      VERSION: docker
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      ORCHESTRATOR_URL: http://plex-orchestrator:3500
      PMS_SERVICE: plex     # This service. If you disable Local Relay then you must use PMS_IP instead
      PMS_PORT: "32400"
      TRANSCODE_OPERATING_MODE: remote #(local|remote|both)
      TRANSCODER_VERBOSE: "1"   # 1=verbose, 0=silent
      LOCAL_RELAY_ENABLED: "1"
      LOCAL_RELAY_PORT: "32499"
    healthcheck:
      test: curl -fsS http://localhost:32400/identity > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    volumes:
      - /root/docker-containers/clusterplex/config:/config
      - /mnt/plex_tvshows:/tvshows
      - /mnt/plex_movies:/movies
      - /mnt/plex_tvshows/Plex/Transcode:/transcode
    ports:
      - 32499:32499     # LOCAL_RELAY_PORT
      - 32400:32400
      - 3005:3005
      - 8324:8324
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp

  plex-orchestrator:
    image: ghcr.io/pabloromeo/clusterplex_orchestrator:latest
    deploy:
      placement:
        constraints:
          - node.labels.orchestrator ==  true
      update_config:
        order: start-first
    healthcheck:
      test: curl -fsS http://localhost:3500/health > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    environment:
      TZ: America/Los_Angeles
      LISTENING_PORT: 3500
      WORKER_SELECTION_STRATEGY: "LOAD_RANK" # RR | LOAD_CPU | LOAD_TASKS | LOAD_RANK (default)
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3500:3500

  plex-worker:
    image: ghcr.io/linuxserver/plex:latest
    hostname: "plex-worker-{{.Node.Hostname}}"
    deploy:
      mode: replicated
      replicas: 6
      placement:
        constraints:
          - node.labels.worker == true
    environment:
      DOCKER_MODS: "ghcr.io/pabloromeo/clusterplex_worker_dockermod:latest"
      VERSION: docker
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      LISTENING_PORT: 3501      # used by the healthcheck
      STAT_CPU_INTERVAL: 2000   # interval for reporting worker load metrics
      ORCHESTRATOR_URL: http://plex-orchestrator:3500
      EAE_SUPPORT: "1"
    healthcheck:
      test: curl -fsS http://localhost:3501/health > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 240s
    volumes:
      - /mnt/plex_tvshows:/tvshows
      - /mnt/plex_movies:/movies
      - /mnt/plex_tvshows/Plex/Transcode:/transcode

**Comment by konSMASH** [comment]
I will add that I have gone the route of disabling the local relay and adding the PMS_IP in and it still doesn't seem to work. I am using CIFS to mount a NAS for my transcode location.

**Comment by konSMASH** [comment]
I will add that I have gone the route of disabling the local relay and adding the PMS_IP in and it still doesn't seem to work. I am using CIFS to mount a NAS for my transcode location.

**Comment by pabloromeo** [comment]
Hi! One thing I'm seeing, is that you have TRANSCODE_OPERATING_MODE set to local, which means it will always only transcode in your PMS and not on workers.
Try setting that to either `remote` or `both` to see if remote transcodes start working.
Also, you can try the current experimental build instead of latest.

Meaning in the dockermods for both pms and the worker, change `:latest` for `:experimental`.
That build is using a more up to date EAE as well as some changes regarding how EAE is triggered and how child processes are monitored.

**Comment by konSMASH** [comment]
Sorry, I updated my yml file to the correct settings when I was having issues. local was there as it was the only way to make it so Plex functioned.

These are the settings I have tried so far to no avail:
- Changing branch to experimental
- Swapping between remote and both for the operating mode.
- Changing PMS_SERVICE from plex PMS_IP and adding the Plex server IP.
- Changing anything related to plex-orchestrator as a service name to the IP of the orchestrator server. (Since I have it set to the same server as the Plex server)
- Bashing into the Plex container and making sure I can get to plex-orchestrator on port 3500 by running the command "nc -v -z -w 2 plex-orchestrator 3500"
- Completely disabling the local relay and using the PMS_IP, disabling "Enable Relay" within Plex, and adding the worker servers under "List of IP addresses and network that are allowed without auth"
- Changing around the deployment constraints. (The only time this worked was when I used replicas and it replicated a worker to the PMS database server. Basically all that did was a backdoor local transcode)
-  Moved codecs to a shared path between all servers within the swarm.

I am at a loss for anything else to test as my Linux knowledge isn't amazing by any means. ClusterPlex was the sole thing that actually got me into Linux. :)

If you have any other ideas I could try please let me know.

**Comment by pabloromeo** [comment]
Can you scale the worker replicas to 1, and then review logs when attempting to transcode? 
There should be something valuable in the worker logs and in plex's UI Console logs. 
Nothing should be stopping CPU transcoding other than a config issue.

**Comment by pabloromeo** [comment]
From what I can see in the worker logs, it's actually transcoding fine and it seems the entire transcode finished.

For some reason PMS doesn't seem to be picking up on the segments being written to the shared transcode path.

How is that being shared, NFS? Or CIFS/SMB?

**Comment by konSMASH** [comment]
> From what I can see in the worker logs, it's actually transcoding fine and it seems the entire transcode finished.
> 
> For some reason PMS doesn't seem to be picking up on the segments being written to the shared transcode path.
> 
> How is that being shared, NFS? Or CIFS/SMB?

Shared via a CIFS mount.

**Comment by pabloromeo** [comment]
From what I can see in the worker logs, it's actually transcoding fine and it seems the entire transcode finished.

For some reason PMS doesn't seem to be picking up on the segments being written to the shared transcode path.

How is that being shared, NFS? Or CIFS/SMB?

**Comment by pabloromeo** [comment]
Any chance you could try sharing it over NFS? I've seen other issues reported in the past where CIFS wasn't playing very nice with the way plex monitors the file system for new transcoding segments.

**Comment by konSMASH** [comment]
> Any chance you could try sharing it over NFS? I've seen other issues reported in the past where CIFS wasn't playing very nice with the way plex monitors the file system for new transcoding segments.

I'll see if I can get that done this evening or early tomorrow morning and test. Once I test I'll let you know.

**Comment by pabloromeo** [comment]
Can you go into `Plex's Server Settings` -> `Manage` -> `Console`, and see what messages come up there during your attempt at transcoding?
Also if no errors pop up in that test you can enable Verbose logging in Plex, in `Plex's Server Settings` -> `Settings` -> `General` where you have both Debug, and Verbose logging that can be enabled. They are quite noisy in the Console log, but might shed some light on what's going on.

**Comment by konSMASH** [comment]
Verbose logging is enabled. You are right, it is very noisy, lol. I am seeing no errors and a lot of text showing transcode requests and completions.
