### ISSUE TITLE
Keep live tv transcode sessions on the local PMS

### ISSUE THREAD

**Issue by jarneson33** [pabloromeo/clusterplex#264]
**Describe the bug**
When trying to transcode live tv video feeds whether it be for DVR recordings or live tv watching, the remote transcoding introduces too much latency which results in A. Destroyed DVR recordings that jump all around or B. A stuttering live tv watching experience.

**To Reproduce**
1. Setup Live TV & DVR on your PMS
2. Start streaming a live tv channel OR setup some recordings
3. Watch the live feed or the DVR recordings

**Expected behavior**
When a transcode session starts and contains 'live-tv' in the transcode session name ignore sending the request to the orchestrator and keep the request on the local PMS

**Desktop (please complete the following information):**
 - OS: Docker Swarm

**Comment by pabloromeo** [comment]
Hopefully I'll find some time soon to add this filter so live TV doesn't break.
Unfortunately I don't have live TV set up so I might have to implement it on the experimental branch and maybe have you test to make sure it works prior to merging to main.
