### ISSUE TITLE
clusterplex deploy throught docker mod failed deploy pms container

### ISSUE THREAD

**Issue by rmicheli66** [pabloromeo/clusterplex#265]
**Describe the bug**
deploy clusterplex with swarm dockermod method failed when deploy pms container with error and inter in infinite deploy loop.

**To Reproduce**
1. Deploy stack (add stack) trogh portainer plugin with **docker-compose_mod.yml** file
2. services WRK1, WRK2 and orchestrator sucseffuly deployed
3. Service pms fail after 2 minuts with error 137
<img width="979" alt="Screenshot 2023-11-01 at 15 32 13" src="https://github.com/pabloromeo/clusterplex/assets/24733666/7a8b85cc-19ad-40e9-bdf1-0d329d83fcc8">
'

**Expected behavior**

**Screenshots**
See attach
<img width="939" alt="Screenshot 2023-11-01 at 15 47 16" src="https://github.com/pabloromeo/clusterplex/assets/24733666/c279c347-60e3-465b-887c-ee00f82c6759">
<img width="979" alt="Screenshot 2023-11-01 at 15 32 13" src="https://github.com/pabloromeo/clusterplex/assets/24733666/7a8b85cc-19ad-40e9-bdf1-0d329d83fcc8">

**Desktop (please complete the following information):**
 - OS: Docker Desktop (swarm) on OSX Ventura
 - 

**Additional context**
I think the problem is when try to install **node.j:lts.** In fact with n**node.j:latest**  (bash n latest in 92-install-dependencies) clusterplex deploy with dockermod works correctly.

**My docker-compose_mod.yml:**
version: '3.8'

services:
  plex:
    image: ghcr.io/linuxserver/plex:latest
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DOCKER_MODS: "ghcr.io/pabloromeo/clusterplex_dockermod:latest"
      VERSION: docker
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      ORCHESTRATOR_URL: http://plex-orchestrator:3500
      PMS_SERVICE: plex     # This service. If you disable Local Relay then you must use PMS_IP  istead
      PMS_PORT: "32400"
      TRANSCODE_OPERATING_MODE: both #(local|remote|both)
      TRANSCODER_VERBOSE: "1"   # 1=verbose, 0=silent
      LOCAL_RELAY_ENABLED: "1"
      LOCAL_RELAY_PORT: "32499"
    healthcheck:
      test: curl -fsS http://localhost:32400/identity > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    volumes:
      - /Users/rmicheli/lab/Plex/plex/config:/config 
      - /Users/rmicheli/lab/Plex/wkr/codecs:/codecs # (optional)
      - /Users/rmicheli/lab/Plex/plex/tv:/data/tv
      - /Users/rmicheli/lab/Plex/plex/movies:/data/movies
      - /Users/rmicheli/lab/Plex/plex/music:/data/music
      - /Users/rmicheli/lab/Plex/wkr/transcode:/transcode # (optional)
    ports:
      - 32499:32499     # LOCAL_RELAY_PORT
      - 32400:32400
      - 3005:3005
      - 8324:8324
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp

  plex-orchestrator:
    image: ghcr.io/pabloromeo/clusterplex_orchestrator:latest
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
    healthcheck:
      test: curl -fsS http://localhost:3500/health > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    environment:
      TZ: Europe/London
      LISTENING_PORT: 3500
      WORKER_SELECTION_STRATEGY: "LOAD_RANK" # RR | LOAD_CPU | LOAD_TASKS | LOAD_RANK (default)
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3500:3500

  plex-worker:
    image: ghcr.io/linuxserver/plex:latest
    hostname: "plex-worker-{{.Node.Hostname}}"
    deploy:
      mode: replicated
      replicas: 2
    environment:
      DOCKER_MODS: "ghcr.io/pabloromeo/clusterplex_worker_dockermod:latest"
      VERSION: docker
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      LISTENING_PORT: 3501      # used by the healthcheck
      STAT_CPU_INTERVAL: 2000   # interval for reporting worker load metrics
      ORCHESTRATOR_URL: http://plex-orchestrator:3500
      EAE_SUPPORT: "1"
    healthcheck:
      test: curl -fsS http://localhost:3501/health > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 240s
    volumes:
      - /Users/rmicheli/lab/Plex/wkr/codecs:/codecs # (optional)
      - /Users/rmicheli/lab/Plex/plex/tv:/data/tv
      - /Users/rmicheli/lab/Plex/plex/movies:/data/movies
      - /Users/rmicheli/lab/Plex/plex/music:/data/music
      - /Users/rmicheli/lab/Plex/wkr/transcode:/transcode 
      - /Users/rmicheli/lab/Plex/wkr/config:/config

**Comment by pabloromeo** [comment]
Hi!
Do you have the container logs (PMS) from the startup process, which would show what is happening during the nodejs install?
