### ISSUE TITLE
Transcoding not working either locally on the PMS or Remotly when using the transcoder-shim.sh

### ISSUE THREAD

**Issue by FlanniganColum** [pabloromeo/clusterplex#268]
**Describe the bug**
I get an error message on plex player when transcoding is happening. I have everything configured as expected and when i have the transcoder-shim.sh in place it does not work either when i have the transcoder.js set for "local", "remote" or "both". When i remove the transcoder-shim.sh and restore the plex original everything is working..

I have copied the latest files from the repo but nothing is working, is there anything i can look at to try and identify the issue??

**Desktop (please complete the following information):**
 - OS: Linux CentOS
 - Version 7

**Additional context**

**Comment by pabloromeo** [comment]
Log files of the containers should have some relevant information.
There shouldn't be a need for manually copying files though, as the containers are self-sufficient.
