### ISSUE TITLE
'H4 not supported' error on Chromecast

### ISSUE THREAD

**Issue by christensenjairus** [pabloromeo/clusterplex#272]
**Describe the bug**
'H4 not supported' error on chromecasts when transcoding.

**To Reproduce**
1. Use clusterplex with no special installation configuration
2. Play a movie on plex using a chromecast
3. Change from original quality to a transcode, 720p HIGH for example.
4. Error occurs instead of playing

**Expected behavior**
Movie to play with no error.

**Additional context**
This does not occur on latest plex docker install. I have normal dockerized plex running on another server, and the movie plays transcoded just fine.

Seems this is a common issue with plex and chromecasts when plex is using older codec versions. Most of the plex issues I've seen are from around 5 years ago. Seems the codecs aren't up to date.

**Comment by pabloromeo** [comment]
It could be that we are missing some particular codecs when initializing the worker.
When using the regular Plex install, can you identify which codecs plex has downloaded in its codecs folder?

**Comment by christensenjairus** [comment]
I've got EasyAudioEncoder-1978 and a handful of other .so files

![image](https://github.com/pabloromeo/clusterplex/assets/58751387/29791ace-8cb1-49b9-a978-1d5a38ca7288)
