### ISSUE TITLE
Help with running on docker swarm with Raspberry PI cluster

### ISSUE THREAD

**Issue by ronyv89** [pabloromeo/clusterplex#281]
I am very new to Docker Swarm. Don't know whether I am doing this right. There is very little documentation on what we need to change in the docker compose file. Is there a step by step tutorial for this? I have a 2 node Raspberry PI cluster(set to upgraded to 3). I would love to deploy this. But I need help setting it up

**Comment by pabloromeo** [comment]
Hi!
Unfortunately I've never gotten around to posting a step by step tutorial. Also it would differ quite a bit depending on the hardware config and layout.
But for the most basic install with cpu transcoding the compose file can mostly stay as is.
Things you'd have to configure are the TZ env vars for your timezone, and the volume mappings of both the plex service and the workers.
The plex service has two important mappings. One is plex's config path. Which you'll probably want to map to a docker volume or something like that. So it survives container recreations. And then the network mappings for where your content for the libraries will be. 

What you'll need is to have some form of network sharing across them. Which could be NFS, CIFS, etc. That's to share the media content across plex and the workers, and they need to be mapped to the same paths.
There's also a bit more info on each environment variable in the docs, as well as more explanation on the network sharing.
Sorry if this explanation is a bit all over the place, I'm typing it from a phone at the moment :)
