### ISSUE TITLE
custom Plex Transcode (ffmpeg) for advanced server side transcode

### ISSUE THREAD

**Issue by efschu** [pabloromeo/clusterplex#282]
**Is your feature request related to a problem? Please describe.**
I try to "extend" Plex Transcode (which actual is "only" ffmpeg) to make it use of RIFE using tensorrt or, python script as input directly, on the server where the "strong" hardware sits, so I can play my content with high frame rate anywhere in my network

**Describe the solution you'd like**
a description of how to build and use a custom Plex Transcode with extended arguments (tensorrt)

**Describe alternatives you've considered**
I looked into plex-mpv-shim - built it with the corresponding features, it works, but the interpolation must be done on the clientside - and not all clients have sufficient power to do so

I already tried this one https://github.com/ForsakenNGS/raspi-plex-transcode but it didnt work (maybe to old - or me to stupid)

I used this one for upscaling/interpolation https://github.com/styler00dollar/VSGAN-tensorrt-docker but I want to do it on the fly and not to transcode all my media

*example with ffmpeg and python script as input*

ffmpeg -f vapoursynth -i inference.py example.mkv -y

*example with ffmpeg trt plugin + nvenc*

ffmpeg -hwaccel cuda -hwaccel_output_format cuda -i input.mp4 -vf scale_npp=1280:720,format_cuda=rgbpf32le,tensorrt=my_engine.engine,format_cuda=nv12 -c:v hevc_nvenc -preset lossless output.mkv -y

*example with ffmpeg trt plugin + hwdownload (cpu encoding)*

ffmpeg -hwaccel cuda -hwaccel_output_format cuda -i input.mp4 -vf format_cuda=rgbpf32le,tensorrt=my_engine.engine,format_cuda=nv12,hwdownload,format=nv12 -vcodec ffv1 output.mkv -y

**Additional context**

**Comment by JRodez** [comment]
it's maybe possible to replace ffmpeg with a hook, like a file containg
```bash
#!/usr/bin/env bash

ARGS=$@
# hook on args
custom_transcoder_bin $ARGS

```

**Comment by efschu** [comment]
I replaced ffmpeg binary with a python script which does what I want.
