### ISSUE TITLE
Show not playing and continues logging

### ISSUE THREAD

**Issue by ColumFlannigan** [pabloromeo/clusterplex#31]
**Describe the bug**
So when i use this the show does not play however i am not using the PMS in docker but i have a specific VM that has been pre-built and in use for some time. The error i keep seeing in the Orch logs is below. The error comes up for both my 01 and 02 workers.

Client connected: CYRO6j_K8WdQOe4SAAGQ
Client disconnected: tW0yBEgTTd6K-U_uAAGP
Unregistering worker at socket tW0yBEgTTd6K-U_uAAGP
Killing pending tasks for worker: 44558382-25c1-496c-bdf3-2d036fb66506
Unregistering worker 44558382-25c1-496c-bdf3-2d036fb66506|OS-Plex-Cluster_plex-worker-ie01-dnp01
Registering worker 44558382-25c1-496c-bdf3-2d036fb66506|OS-Plex-Cluster_plex-worker-ie01-dnp01
Registered new worker: 44558382-25c1-496c-bdf3-2d036fb66506|OS-Plex-Cluster_plex-worker-ie01-dnp01
Client connected: ooruJyadlQf_jMZaAAGR

**To Reproduce**
This is a fresh install

**Expected behavior**
When i try and play a movie/show that is transcoding it just keeps refreshing. I can see on the worker node the transcoding is running but not playing, I also see the above logs continue to print on the orch server logs

**Screenshots**

**Desktop (please complete the following information):**
 - OS: PMS - CentOS 7,  Docker Swarm 19.03.13,
 - Version 7.8, 19.03.13

**Additional context**
On the client side
[libx264 @ 0x1a3e980] frame P:91    Avg QP:19.88  size:  1915
[libx264 @ 0x1a3e980] frame B:211   Avg QP:21.50  size:   444
[libx264 @ 0x1a3e980] consecutive B-frames:  7.4%  1.9%  7.8% 82.8%
[libx264 @ 0x1a3e980] mb I  I16..4:  6.4% 72.2% 21.5%
[libx264 @ 0x1a3e980] mb P  I16..4:  4.3% 30.7%  3.5%  P16..4: 17.8% 13.4%  6.4%  0.0%  0.0%    skip:23.9%
[libx264 @ 0x1a3e980] mb B  I16..4:  1.1%  6.3%  0.1%  B16..8: 21.4%  4.5%  0.3%  direct: 2.9%  skip:63.3%  L0:29.7% L1:49.5% BI:20.8%
[libx264 @ 0x1a3e980] 8x8 transform intra:79.9% inter:34.8%
[libx264 @ 0x1a3e980] coded y,uvDC,uvAC intra: 46.0% 21.2% 1.6% inter: 6.6% 2.3% 0.0%
[libx264 @ 0x1a3e980] i16 v,h,dc,p: 18% 18%  9% 55%
[libx264 @ 0x1a3e980] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 27% 22% 26%  6%  3%  4%  3%  5%  4%
[libx264 @ 0x1a3e980] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 20% 24% 18%  7%  6%  5%  6%  6%  7%
[libx264 @ 0x1a3e980] i8c dc,h,v,p: 74% 13% 11%  1%
[libx264 @ 0x1a3e980] Weighted P-Frames: Y:20.9% UV:4.4%
[libx264 @ 0x1a3e980] kb/s:183.32
[aac @ 0x1a3fd80] Qavg: 13036.340
[AVIOContext @ 0x17d3940] Statistics: 15709280 bytes read, 4 seeks
Conversion failed!
Completed transcode
Removing process from taskMap
Worker disconnected
Worker connected on socket 6vgDF09QLvYeqseSAAGh

**Extra**
So as mentioned i have taken the PMS code you have and installed on the my PMS VM, which works when TRANSCODE_OPERATING_MODE = 'local' so that shows your pms code works great for that as it redirects to the local transcoder binary, but for some reason i cannot get the docker worker,orch working correctly..

**Comment by ColumFlannigan** [comment]
Closing this looks like i needed to add the docker VLAN IP's to PMS "List of IP addresses and networks that are allowed without auth" and everything seems to be stable now

**Comment by pabloromeo** [comment]
Awesome! Glad to hear that resolved the issue :)
