### ISSUE TITLE
ORCHESTRATOR question. 

### ISSUE THREAD

**Issue by Nullvoid3771** [pabloromeo/clusterplex#331]
Do I need to change the orchestrator url? When I go to the url nothing happens so I'm wondering if their is any setup on my end to make this local domain work? 

"The url where the orchestrator service can be reached (ex: http://plex-orchestrator:3500)"

**Comment by Nullvoid3771** [comment]
or is "plex-orchestrator" a placeholder for the ip the orchestrator lives on which leads me to another question. If that's the case what happens when orchestrator moves to another system in a docker swarm, wouldn't the url change? or can we put multiple?

**Comment by pabloromeo** [comment]
It refers to the service name. So in Swarm it would resolve even if it moves from node. The same applies when it's a kubernetes Service.

The orchestrator is used for internal system to system communication, you won't find content there except for the healthcheck.

**Comment by Nullvoid3771** [comment]
> It refers to the service name. So in Swarm it would resolve even if it moves from node. The same applies when it's a kubernetes Service.
> 
> The orchestrator is used for internal system to system communication, you won't find content there except for the healthcheck.

Ah okay. So defining a ip is the wrong way to go. What I did was in env pms and worker I defined it as http://192.168.1.x:3500 and then increased the plex-orchestrator replication to two so it would be on both nodes. And at least one would resolve. So guessing I didn’t have to do that and could have kept it as http://plex-orchestrator:3500/ since it’s internal.

**Comment by pabloromeo** [comment]
Ah, no, don't do it that way. You must have a single orchestrator, that will talk to all workers and receive requests from PMS.
