### ISSUE TITLE
Can't Transcode to workers. 

### ISSUE THREAD

**Issue by Nullvoid3771** [pabloromeo/clusterplex#332]
Not sure how to resolve this error in plex logs. 

Little insight on my setup I'm using proxmox to host vms. 2 vm's total on two nodes on different systems running in docker swarm. 

I've attempted to disable firewalls & allow packet forwarding on all system hosts / vms. no luck. any idea?

NetworkServiceBrowser: Error sending out discover packet from 10.0.0.39 to 10.0.0.255: Operation not permitted

**Comment by Nullvoid3771** [comment]
also getting so probably related. 

JobPoster connected, announcing

Orchestrator requesting pending work

Sending request to orchestrator on: http://plex-orchestrator:3500

Distributed transcoder failed, calling local

**Comment by Nullvoid3771** [comment]
Received task request
EAE_ROOT => "/tmp/pms-2bad85a5-e295-42ce-b5f6-3e07de05f105/EasyAudioEncoder"
EAE Support - EAE already running
CWD path doesn't seem to exist. Plex should have created this path before-hand, so you may have an issue with your shares => "/config/Library/Application Support/Plex Media Server/Cache/Transcode/Sessions/plex-transcode-26k61s2ohb6ux3zspu2hbe3s-37bd8433-38a8-47f5-8e1f-e0c23e838168"
Transcoding failed:
Error: spawn /usr/lib/plexmediaserver/Plex Transcoder ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
Orchestrator notified
Removing process from taskMap
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /usr/lib/plexmediaserver/Plex Transcoder',
  path: '/usr/lib/plexmediaserver/Plex Transcoder',
  spawnargs: [
    '-codec:0',
    'hevc',
    '-codec:1',
    'eac3_eae',
    '-eae_prefix:1',
    '26k61s2ohb6ux3zspu2hbe3s_',
    '-ss',
    '938',
    '-analyzeduration',
    '20000000',
    '-probesize',
    '20000000',
    '-i',
    '/data/movies/Movies/[Redacted],
    '-filter_complex',
    '[0:0]scale=w=720:h=360:force_divisible_by=4[0];[0]format=pix_fmts=yuv420p|nv12[1]',
    '-map',
    '[1]',
    '-codec:0',
    'libx264',
    '-crf:0',
    '20',
    '-maxrate:0',
    '1712k',
    '-bufsize:0',
    '3424k',
    '-r:0',
    '30',
    '-preset:0',
    'veryfast',
    '-x264opts:0',
    'subme=3:me_range=4:rc_lookahead=10:me=hex',
    '-filter_complex',
    "[0:1] aresample=async=1:ochl='stereo':rematrix_maxval=0.000000dB:osr=48000[2]",
    '-map',
    '[2]',
    '-metadata:s:1',
    'language=eng',
    '-codec:1',
    'libopus',
    '-b:1',
    '178k',
    '-f',
    'segment',
    '-segment_format',
    'matroska',
    '-segment_format_options',
    'live=1',
    '-segment_time',
    '1',
    '-segment_header_filename',
    'header',
    '-segment_start_number',
    '0',
    '-segment_list',
    'http://plex:32499/video/:/transcode/session/26k61s2ohb6ux3zspu2hbe3s/37bd8433-38a8-47f5-8e1f-e0c23e838168/manifest?X-Plex-Http-Pipeline=infinite',
    '-segment_list_type',
    'csv',
    '-segment_list_unfinished',
    '1',
    '-segment_list_size',
    '5',
    '-segment_list_separate_stream_times',
    '1',
    '-avoid_negative_ts',
    'disabled',
    '-map_metadata:g',
    '-1',
    '-map_metadata:c',
    '-1',
    '-map_chapters',
    '-1',
    'chunk-%05d',
    '-start_at_zero',
    '-copyts',
    '-y',
    '-nostats',
    '-loglevel',
    'verbose',
    '-loglevel_plex',
    'verbose',
    '-progressurl',
    'http://plex:32499/video/:/transcode/session/26k61s2ohb6ux3zspu2hbe3s/37bd8433-38a8-47f5-8e1f-e0c23e838168/progress'
  ]
}
Transcoder close: child process exited with code -2

**Comment by Nullvoid3771** [comment]
hm maybe a permission issue

**Comment by pabloromeo** [comment]
Ah, yes, network shares are mandatory.
For hardware transcoding support there are a few others, such as Drivers and Cache.
There are other closed issues here describing those extra network shares.

**Comment by pabloromeo** [comment]
The "error sending out discovery packet" I believe is a non-issue.
Can't remember exactly what plex functionality that is (maybe discovering of client players through udp broadcasts or something like that, which wouldn't work on docker bridge networks), but it doesn't affect the application.

**Comment by Nullvoid3771** [comment]
@pabloromeo 
> Ah, yes, network shares are mandatory. For hardware transcoding support there are a few others, such as Drivers and Cache. There are other closed issues here describing those extra network shares.

Can you confirm this setup is correct I've added comments below to explain in more detail. 

![plexnet](https://github.com/user-attachments/assets/cc160769-fd4d-4304-9d85-ee97fa122682)
![plexnet2](https://github.com/user-attachments/assets/273f1d1e-13c7-4049-acd1-27d8d90a3270)
![secure](https://github.com/user-attachments/assets/57d9cd36-93b3-454b-bef4-e1caff3ca680)


version: '3.8'

services:
  plex:
    image: ghcr.io/linuxserver/plex:latest
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DOCKER_MODS: "ghcr.io/pabloromeo/clusterplex_dockermod:latest"
      VERSION: docker
      PUID: 1000
      PGID: 1000
      TZ: America/Toronto
      ORCHESTRATOR_URL: http://plex-orchestrator:3500
      PMS_SERVICE: plex     # This service. If you disable Local Relay then you must use PMS_IP instead
      PMS_PORT: "32400"
      TRANSCODE_OPERATING_MODE: local #(local|remote|both)         #Works only in local PMS mode. 
      TRANSCODER_VERBOSE: "1"   # 1=verbose, 0=silent
      LOCAL_RELAY_ENABLED: "1"
      LOCAL_RELAY_PORT: "32499"
      FORCE_HTTPS: "0"
    devices:
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    healthcheck:
      test: curl -fsS http://localhost:32400/identity > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    volumes:
       - type: bind                        #config only shared with master node as per instuctions. This is a local portainer/docker volume.
         source: $HOST/var/lib/docker/volumes/plexvolume/_data
         target: /config
       - type: bind
         source: $HOST/media/MoviesOther
         target: /data/moviesother
       - type: bind               #These cifs mounts read fine. No op-locks. 
         source: $HOST/media/Movies
         target: /data/movies
       - type: bind
         source: $HOST/media/TvShowsMore
         target: /data/tvshowsmore
       - type: bind 
         source: $HOST/media/TvShows
         target: /data/tvshows
       - type: bind 
         source: $HOST/media/Main-Archive
         target: /data/main-archive
       - type: bind                         #SMB permission 0777, noticed nothing getting to workers or transcodes getting to this folder.
         source: $HOST/media/MoviesOther/Dave-NAS/Plex/config/Library/Application Support/Plex Media Server/Cache/Transcode/Sessions
         target: /transcode
     
    ports:        #All ports in proxmox, and vms have been allowed including 3501 which was not stated, but since it listens. 
      - 32499:32499     # LOCAL_RELAY_PORT
      - 32400:32400
      - 3005:3005
      - 8324:8324
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp

  plex-orchestrator:
    image: ghcr.io/pabloromeo/clusterplex_orchestrator:latest
    deploy:
      mode: replicated
      replicas: 0       #This is zero since I can only get local transcoding working atm. 
      update_config:
        order: start-first
    healthcheck:
      test: curl -fsS http://localhost:3500/health > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    environment:
      TZ: America/Toronto
      LISTENING_PORT: 3500
      WORKER_SELECTION_STRATEGY: "LOAD_RANK" # RR | LOAD_CPU | LOAD_TASKS | LOAD_RANK (default)
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3500:3500

  plex-worker:
    image: ghcr.io/linuxserver/plex:latest
    hostname: "plex-worker-{{.Node.Hostname}}"
    deploy:
      mode: replicated
      replicas: 0 #This is zero since I can only get local transcoding working atm. 
    environment:
      DOCKER_MODS: "ghcr.io/pabloromeo/clusterplex_worker_dockermod:latest"
      VERSION: docker
      PUID: 1000
      PGID: 1000
      TZ: America/Toronto
      LISTENING_PORT: 3501      # used by the healthcheck
      STAT_CPU_INTERVAL: 2000   # interval for reporting worker load metrics
      ORCHESTRATOR_URL: http://plex-orchestrator:3500
      EAE_SUPPORT: "1"
    devices:
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    healthcheck:
      test: curl -fsS http://localhost:3501/health > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 240s
    volumes: 
       - type: bind
         source: $HOST/media/MoviesOther
         target: /data/moviesother
       - type: bind 
         source: $HOST/media/Movies
         target: /data/movies
       - type: bind                              #These cifs mounts read fine. No op-locks.
         source: $HOST/media/TvShowsMore
         target: /data/tvshowsmore
       - type: bind 
         source: $HOST/media/TvShows
         target: /data/tvshows
       - type: bind 
         source: $HOST/media/Main-Archive
         target: /data/main-archive
       - type: bind
         source: $HOST/media/MoviesOther/Dave-NAS/Plex/codecs
         target: /codecs
       - type: bind             ##SMB permission 0777, noticed nothing getting to workers or transcodes getting to this folder.
         source: $HOST/media/MoviesOther/[Redacted]-NAS/Plex/config/Library/Application Support/Plex Media Server/Cache/Transcode/Sessions
         target: /transcode  
       
       #Dev instructed me that Drivers need to be shared, I see a reference in closed issues for Kubernetes, but not Docker swarm. Maybe not needed, since /config isn't shared. 
       #Main issue seems to maybe be /transcode via SMB3, however using cephs is a issue since I don't have spare dedicated drives for this. 
       #I've allowed packet forwarding in proxmox node hosts. My docker lives within a 2 vm's on different cluster nodes to allow firewall to work. 
 

==============================================================

Samba config. 

[global]
	writeable = yes
	passwd program = /usr/bin/passwd %u
	read raw = no
	max log size = 1000
	default = global
	load printers = no
	logging = file
	inherit acls = yes
	panic action = /usr/share/samba/panic-action %d
	delete readonly = yes
	pam password change = no
	server string = %h server (Samba, Ubuntu)
	aio write size = 1
	min protocol = smb2
	getwd cache = yes
	large readwrite = yes
	netbios name = RackServer2
	write raw = no
	bind interfaces only = yes
	aio read size = 1
	log level = 1
	enhanced browsing = Yes
	server role = standalone server
	locking = no
	log file = /var/log/samba/log.%m
	workgroup = WORKGROUP
	map to guest = bad user
	kernel oplocks = no
	interfaces = "192.168.1.x/255.255.255.0;speed=2000000,capability=RSS" "169.254.x.x/255.255.0.0;speed=5000000,capability=RSS" "127.0.0.1/255.0.0.0;speed=5000000,capability=RSS"
	local master = yes
	revalidate = yes
	encrypt passwords = true
	server signing = mandatory
	use sendfile = true
	os level = 20 
	server multi channel support = yes
	inherit owner = yes
	inherit permissions = yes
	unix password sync = yes
	smb encrypt = mandatory
	obey pam restrictions = yes
	usershare allow guests = yes
	socket options = SO_BROADCAST TCP_NODELAY IPTOS_LOWDELAY
	oplocks = no
	client signing = mandatory

[PlexConfig]
	user = [Redacted],nobody,@nogroup,[Redacted]
	force create mode = 0777
	valid users = [Redacted],[Redacted],[Redacted],nobody
	write list = nobody,[Redacted],[Redacted],@nogroup
	path = /media/MoviesOther/[Redacted]-NAS/Plex
	create mode = 0777
	directory mode = 0777
	force directory mode = 0777
	vfs objects = io_uring

#Media folders work as intended so didn't include them.

**Comment by Nullvoid3771** [comment]
![plexerror](https://github.com/user-attachments/assets/35f2c224-4b97-49b6-9afb-f37ae0d06b2b)

I've tried adding a /drivers folder or even a /config folder for the workers no go. with or without these I get this error above.

**Comment by Nullvoid3771** [comment]
@pabloromeo 

Apparently this is a issue with Intel-Quicksync. Because devices: /dev/dri:dev/dri is not used in **docker swarm** it cannot look for video drivers for the gpu/cpu? So maybe add a caveat that states that this will not work on amd/intel-quicksync/software encode or any gpu **Except NVIDIA**. Unless you have more info on how to fix this, but perhaps a issue with Proxmox virtualisation.

**Comment by Nullvoid3771** [comment]
This here is apparently a workaround for the issue of docker swarm not working with intel-quicksync 

https://pastebin.com/XY7GP18T

**Comment by Nullvoid3771** [comment]
Orchestrator receives the task, but the workers do not. No idea why.

Initializing orchestrator

Using Worker Selection Strategy: LOAD_RANK

Stream-Splitting: DISABLED

Setting up websockets

Ready

Server listening on port 3500

Client connected: w6IQ1IDAne2vCNB-AAAB

Registering worker 1e73f8be-901b-42c7-866b-3ac77db2d12d|[Redacted-pcname]

Registered new worker: 1e73f8be-901b-42c7-866b-3ac77db2d12d|[Redacted-pcname]

Client connected: vkKB0peRsDr67e8FAAAD

Registering worker c5a98a53-3d57-4016-aafa-e51b736e1ec6|[Redacted-pcname]

Registered new worker: c5a98a53-3d57-4016-aafa-e51b736e1ec6|[Redacted-pcname]

Client connected: 6ED7DeHQdp4vH_PMAAAF

Registered new job poster: 3e3c8a60-a4f6-4a53-b55d-d674e512dfec|12cb24533837

Creating single task for the job

Queueing job d9cd4b5e-b6bc-4a8b-81e7-648d9bd58c33

Queueing task 6b440e6b-8587-4e19-8d12-87d0006675e2

Running task 6b440e6b-8587-4e19-8d12-87d0006675e2

Forwarding work request to 1e73f8be-901b-42c7-866b-3ac77db2d12d|[redacted]

Received update for task 6b440e6b-8587-4e19-8d12-87d0006675e2, status: received

Client disconnected: w6IQ1IDAne2vCNB-AAAB

Unregistering worker at socket w6IQ1IDAne2vCNB-AAAB

Killing pending tasks for worker: 1e73f8be-901b-42c7-866b-3ac77db2d12d

Received update for task 6b440e6b-8587-4e19-8d12-87d0006675e2, status: done

Task 6b440e6b-8587-4e19-8d12-87d0006675e2 complete, result: false

Task 6b440e6b-8587-4e19-8d12-87d0006675e2 complete

Job d9cd4b5e-b6bc-4a8b-81e7-648d9bd58c33 complete, tasks: 1, result: false

JobPoster notified

Removing job d9cd4b5e-b6bc-4a8b-81e7-648d9bd58c33

Job d9cd4b5e-b6bc-4a8b-81e7-648d9bd58c33 complete

Unregistering worker 1e73f8be-901b-42c7-866b-3ac77db2d12d|plex-worker-[redacted-pcname]

Client disconnected: 6ED7DeHQdp4vH_PMAAAF

Removing job-poster 3e3c8a60-a4f6-4a53-b55d-d674e512dfec|12cb24533837 from pool

**Comment by Nullvoid3771** [comment]
Interestingly whats above isn't even my workers names. 

clusteredplex_plex-worker.1.dvctrexq0pdhxuoaoohjnwo8e

clusteredplex_plex-worker.2.z50z3t6z2mknkajnncrhj7o79

**Comment by Nullvoid3771** [comment]
@pabloromeo 

JobPoster connected, announcing

Orchestrator requesting pending work

Sending request to orchestrator on: http://plex-orchestrator:3500

Distributed transcoder failed, calling local

Error transcoding and local transcode is disabled: TRANSCODE_OPERATING_MODE=remote


----------------------

Setting /transcode to pms & worker on the same node and setting worker to replication 1 means everything will be local to the master node this was done as a test to rule out mounting issues. Ultimately showing the **worker IS the issue** because it is **NOT getting the request**. Now their is no firewall active everything should be working and communicating. Plex is set in settings to the ingress ip for pms. The issue might be the /transcode folder I'm not sure, but to my understanding it is setup correctly. 0755 with user:user (redacted username)

![ingress](https://github.com/user-attachments/assets/ff4d19f0-84d4-4d40-9311-9b28ad1158c5)

![volume](https://github.com/user-attachments/assets/183271a8-c874-47a7-ba01-a097370bfdab)

![ingress2](https://github.com/user-attachments/assets/6425cd19-0ad3-4387-9f96-a56810d19ff6)

![ingress 3](https://github.com/user-attachments/assets/35dec776-faf9-463c-9e4a-bd3cdea111e5)


I can access pms from master node for swarms ip 192.168.1.x:32400 I assume this is the correct way since pms lives on this node. 



volumes:
       - type: bind               
         source: $HOST/var/lib/docker/volumes/plexvolume/_data
         target: /config

       - type: bind                        
         source: $HOST/var/lib/docker/volumes/plexvolume/_data/transcode
         target: /transcode

**Comment by Nullvoid3771** [comment]
Could the issue be that Portainer stacks creates a different subnet from ingress? 

The stack created from https://github.com/pabloromeo/clusterplex/blob/master/docs/docker-swarm/with-dockermods.yaml

creates a new network called clusteredplex_default on 10.0.2.0/24 where ingress is on 10.0.0.0/24 and clusteredplex_default is on 10.0.2.0/24 in its preferred network setting and 172.18.0.0/16 is docker_gwbridge (not sure what that is I seem to have a ton of bridges?)

![IMG_0214](https://github.com/user-attachments/assets/1f9ea879-7e23-4d82-b592-fd93e5535a62)


![IMG_0213](https://github.com/user-attachments/assets/a0883cf2-9b2c-4ff7-909e-c9980db6e699)

**Comment by Nullvoid3771** [comment]
Creating this Clusterplex is probably meant to be done outside of portainer, but I used portainer to make me life easier.  Maybe that’s the wrong way to go about this. A tutorial would be appreciated and really helpful since I can only interpret your instructions to be built in portainer swarm.

**Comment by Nullvoid3771** [comment]
Fixed see: https://github.com/pabloromeo/clusterplex/issues/335
