### ISSUE TITLE
Non ARM version

### ISSUE THREAD

**Issue by slothtechtv** [pabloromeo/clusterplex#36]
First -- This is totally cool and my hats off to you for putting this together! That said I would like to run this without rebuilding the pms container and other bits containers you have on a 64bit intel cpu, is there any chance you could provide a docker stack config / buildout for 64 bit intel cpus? I noticed all of the orchestrator and PMS docker containers you had were for ARM cpus, kind of makes sense .. but I'd like to run the orchestrator and PMS on non ARM architecture.

If "I'm doing this wrong" just let me know :) Thanks!!

**Comment by pabloromeo** [comment]
Hey! Thanks :D
So, I've just added a new build for linux-AMD64, which I suppose should work for you (I haven't tested it).
The new image for the PMS part is now any of the following:
pms-amd64-latest
pms-amd64-1
pms-amd64-1.2
pms-amd64-1.2.8

https://hub.docker.com/r/pabloromeo/clusterplex/tags?page=1&ordering=last_updated&name=pms-amd64

Let me know how it goes!

**Comment by slothtechtv** [comment]
THANK YOU!!! :)

**Comment by slothtechtv** [comment]
What about the orchestrator? :)

**Comment by pabloromeo** [comment]
Good point! :D
Just build the images for the orchestrator as well. Available on v1.2.9 onward, or dev tags.

Hope they all work :D
