### ISSUE TITLE
Error in container start up

### ISSUE THREAD

**Issue by Juxsta** [pabloromeo/clusterplex#60]
Currently getting this error when the containers start. 
`standard_init_linux.go:219: exec user process caused: exec format error`
I’m using the example compose that was linked in the readme with modified bindings.
I’m also running this on unraid, but that shouldn’t affect any docker processes

**Comment by Juxsta** [comment]
My mistake didn’t realize that you compiled arm and non-arm versions

**Comment by pabloromeo** [comment]
FYI, the build process and output images have been moved over to github and ghcr.io just a few days ago.

The new images in this container registry are now multiarch, so one doesn't need to specify the tag for the specific architecture anymore :)
