### ISSUE TITLE
Issues downloading new Codecs

### ISSUE THREAD

**Issue by omega949** [pabloromeo/clusterplex#66]
**Describe the bug**
Issue downloading codecs

**To Reproduce**
Deploy latest version

**Expected behavior**

**Error**

First the start.sh script line  "CLUSTERPLEX_PLEX_CODECS_VERSION=$(strings "Plex Transcoder" | grep -Po '[0-9a-f]{7}-[0-9]{4}$')" returns no codec version, changed "CLUSTERPLEX_PLEX_CODECS_VERSION=$(strings "Plex Transcoder" | grep -i '%s version' | awk '{print $3}')" to get the version which works but still no codecs download

--2021-08-29 12:13:23--  https://downloads.plex.tv/codecs/1.6-02cff92dbb-1/linux-x86_64-standard/libzmbv_decoder.so
Resolving downloads.plex.tv (downloads.plex.tv)... 104.18.12.47, 104.18.13.47, 2606:4700::6812:d2f, ...
Connecting to downloads.plex.tv (downloads.plex.tv)|104.18.12.47|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-08-29 12:13:24 ERROR 404: Not Found.

**Comment by pabloromeo** [comment]
Hey! 
Any chance you could try the latest dev build? There's been a few changes, including the migration to ghcr.io as well as just added support for running clusterplex as dockermods instead of fully customized docker images.
It would be:
PMS => ghcr.io/pabloromeo/clusterplex_pms:dev
Orchestrator => ghcr.io/pabloromeo/clusterplex_orchestrator:dev
Worker => ghcr.io/pabloromeo/clusterplex_worker:dev

The latest build of dev outputted this in my logs (on ARM architecture):

```
2021-08-30 00:15:55	CLUSTERPLEX_PLEX_VERSION => '1.24.1.4931-1a38e63c6'
2021-08-30 00:15:55	CLUSTERPLEX_PLEX_CODECS_VERSION => 'be22e26-3998'
2021-08-30 00:15:55	CLUSTERPLEX_PLEX_EAE_VERSION => 'eae-69c1de6-42'
2021-08-30 00:15:55	PLEX_ARCH => 'armhf'
2021-08-30 00:15:55	CLUSTERPLEX_PLEX_CODEC_ARCH => linux-armv7neon-standard
```

**Comment by pabloromeo** [comment]
Where you able to test the latest version?
The changes have all been merged and tagged with a new release.
I haven't yet found any situation in which codec downloading fails.
Just keep in mind that dockerhub images are not currently being updated. 
Please switch over to the ghcr.io ones as documented in the Readme.

**Comment by omega949** [comment]
No i have not had a chance as im migrating stuff out of an old NAS at
the moment and i have cluster transcoding disabled.. I will give it a
try and i did break your original one out as my PMS is a dedicated
server just put the orch and worker in docker swarm.
-----Original Message-----From: Pablo Romeo ***@***.***>R
eply-To: pabloromeo/clusterplex <
***@***.***>To:
pabloromeo/clusterplex ***@***.***>Cc: omega949 <
***@***.***>, Author ***@***.***>Subject: Re:
[pabloromeo/clusterplex] Issues downloading new Codecs (#66)Date: Thu,
02 Sep 2021 14:49:47 -0700

Where you able to test the latest version?

The changes have all been merged and tagged with a new release.

I haven't yet found any situation in which codec downloading fails.

Just keep in mind that dockerhub images are not currently being
updated.

Please switch over to the ghcr.io ones as documented in the Readme.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pabloromeo** [comment]
Cool, i'll close this one, and if other issues come up in your new environment we'll take a look then.
